spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: translation-project-manager-api
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: application
            client-secret: euRH66K7xvH2xkVtYE91GBAUG7J0KFfc
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/tpm
            user-info-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/certs
            authorization-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/auth
            token-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/token
            user-name-attribute: application
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tpm
          jwk-set-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tpm
    username: application
    password: 1qaz@WSX
  data:
    redis:
      host: localhost
      port: 6379
      password: 1qaz@WSX
      timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: application
  liquibase:
    change-log: db/changelog/db.changelog-master.yml
    default-schema: application

app:
  file-storage:
    minio:
      endpoint: http://localhost:9000
      access-key: admin
      secret-key: 1qaz@WSX
      bucket-name: tpm
  sil-international:
    client:
      code-set-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab
      names-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Name_Index.tab
      macrolanguages-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab
      retirements-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Retirements.tab
  cache:
    countries:
      name: countries-cache
      ttl: 86400
    languages:
      name: languages-cache
      ttl: 86400
    currencies:
      name: currencies-cache
      ttl: 86400
    client-types:
      name: client-types-cache
      ttl: 86400
    clients:
      name: clients-cache
      ttl: 86400

server:
  port: 8080

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
  packages-to-scan: net.nuclearprometheus.tpm.applicationserver

elastic:
  apm:
    enabled: true
    server-url: http://apm-server:8200
    service-name: tpm-application-server
    secret-token: 8a5f8174a5cf7d1a9448c848c8dbfe59047264b1422e274e49723367a0cb8a16
    application-packages: net.nuclearprometheus.tpm.applicationserver
    log-level: INFO
