app:
  file-storage:
    minio:
      endpoint: http://localhost:9000
      access-key: admin
      secret-key: 1qaz@WSX
      bucket-name: tpm
  sil-international:
    client:
      code-set-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab
      names-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Name_Index.tab
      macrolanguages-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab
      retirements-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Retirements.tab
  cache-configurations:
    - name: countries-client-cache
      ttl: 7
      unit: DAYS
    - name: languages-client-cache
      ttl: 7
      unit: DAYS
    - name: currencies-client-cache
      ttl: 1
      unit: DAYS
    - name: client-types-cache
      ttl: 86400
    - name: clients-cache
      ttl: 86400
  keycloak:
    realm: tpm
    auth-server-url: http://localhost:8081
    resource: tpm-backend
    credentials:
      secret: euRH66K7xvH2xkVtYE91GBAUG7J0KFfc

server:
  port: 8080

spring:
  application:
    name: translation-project-manager-api
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tpm
    username: application
    password: 1qaz@WSX
  data:
    redis:
      host: localhost
      port: 6379
      password: 1qaz@WSX
      timeout: 60000
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: application
    open-in-view: false
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    default-schema: application
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak
            client-id: tpm-backend-swagger
            client-secret: 64e4MeOGEV8mD5qNtPmY8154jRwDp7zv
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/tpm
            user-info-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/certs
            authorization-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/auth
            token-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/token
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tpm
          jwk-set-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/certs
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /v3/api-docs/swagger-config
    disable-swagger-default-url: true
  packages-to-scan: net.nuclearprometheus.tpm.applicationserver

management:
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: on
    metrics:
      enabled: on
