app:
  file-storage:
    minio:
      endpoint: http://26.44.49.6:9000
  keycloak:
    auth-server-url: http://26.44.49.6:8081

spring:
  datasource:
    url: jdbc:postgresql://db:5432/tpm
  data:
    redis:
      host: cache
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://26.44.49.6:8081/realms/tpm/protocol/openid-connect/certs

server:
  address: 0.0.0.0
