spring:
  profiles:
    active: '@spring.profiles.active@'
  application:
    name: translation-project-manager-api
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: application
            client-secret: euRH66K7xvH2xkVtYE91GBAUG7J0KFfc
            authorization-grant-type: authorization_code
            scope: openid,profile,email
        provider:
          keycloak:
            issuer-uri: http://localhost:8081/realms/tpm
            user-info-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/userinfo
            jwk-set-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/certs
            authorization-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/auth
            token-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/token
            user-name-attribute: application
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/tpm
          jwk-set-uri: http://localhost:8081/realms/tpm/protocol/openid-connect/certs
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/tpm
    username: application
    password: 1qaz@WSX
  redis:
    host: localhost
    port: 6379
    password: 1qaz@WSX
    timeout: 60000
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: application

app:
  sil-international:
    client:
      code-set-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3.tab
      names-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Name_Index.tab
      macrolanguages-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3-macrolanguages.tab
      retirements-url: https://iso639-3.sil.org/sites/iso639-3/files/downloads/iso-639-3_Retirements.tab
  cache:
    countries:
      name: countries-cache
      ttl: 86400
    languages:
      name: languages-cache
      ttl: 86400
    currencies:
      name: currencies-cache
      ttl: 86400
    client-types:
      name: client-types-cache
      ttl: 86400
    clients:
      name: clients-cache
      ttl: 86400

server:
  port: 8080
